version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'car_test'
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/docker/basedata:/var/lib/postgresql/data
    hostname: 'localhost'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'